# Generated by Django 4.0.4 on 2022-04-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=7),
            preserve_default=False,
        ),
    ]
